version: "3.9"

services:
  client:
    build: .
    volumes:
      - clientvol:/clientdata
    ports:
            - "8181:8181"
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
    - mynetwork

volumes:
  clientvol:

networks:
  mynetwork:
